# Generated by Django 5.1 on 2024-08-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ('-id',), 'verbose_name_plural': 'ACCOUNTS'},
        ),
    ]
