# Generated by Django 5.1 on 2024-09-25 16:48

import business.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('directions', models.CharField(max_length=1024, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('services', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('salon_type', models.CharField(choices=[('barbershop', 'Barbershop'), ('beauty parlour', 'Beauty Parlour')], default='barbershop', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SALONS',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SalonImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=business.models.salon_image_upload_path)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_images', to='business.salons')),
            ],
            options={
                'verbose_name_plural': 'SALONS IMAGES',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('price', models.IntegerField(default=500)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_service', to='business.salons')),
            ],
            options={
                'verbose_name_plural': 'SALON SERVICES',
            },
        ),
    ]
