# Generated by Django 5.1 on 2024-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salons',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salons',
            name='services',
            field=models.TextField(default='Haircutting, Face Wash'),
        ),
    ]
