# Generated by Django 5.1 on 2024-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
