# Generated by Django 5.1 on 2024-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_services_duration_alter_services_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='salon_type',
            field=models.CharField(choices=[('barbershop', 'Barbershop'), ('beauty parlour', 'Beauty Parlour')], default='barbershop', max_length=20),
        ),
    ]
